[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/healthz"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
FLASK_ENV = "production"
FLASK_DEBUG = "False"
DOMAIN = "loteriasinteligente.com.br"
